# Generated by Django 2.0.4 on 2018-05-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20180502_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callerid', models.CharField(max_length=255)),
                ('last_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Product')),
            ],
        ),
    ]
